# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lsah/coding/learning/C++/REF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lsah/coding/learning/C++/REF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lsah/coding/learning/C++/REF/CMakeFiles /Users/lsah/coding/learning/C++/REF//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lsah/coding/learning/C++/REF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named REF

# Build rule for target.
REF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 REF
.PHONY : REF

# fast build rule for target.
REF/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/build
.PHONY : REF/fast

cpp/main.o: cpp/main.cpp.o
.PHONY : cpp/main.o

# target to build an object file
cpp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/main.cpp.o
.PHONY : cpp/main.cpp.o

cpp/main.i: cpp/main.cpp.i
.PHONY : cpp/main.i

# target to preprocess a source file
cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/main.cpp.i
.PHONY : cpp/main.cpp.i

cpp/main.s: cpp/main.cpp.s
.PHONY : cpp/main.s

# target to generate assembly for a file
cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/main.cpp.s
.PHONY : cpp/main.cpp.s

cpp/utils/Image.o: cpp/utils/Image.cpp.o
.PHONY : cpp/utils/Image.o

# target to build an object file
cpp/utils/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/utils/Image.cpp.o
.PHONY : cpp/utils/Image.cpp.o

cpp/utils/Image.i: cpp/utils/Image.cpp.i
.PHONY : cpp/utils/Image.i

# target to preprocess a source file
cpp/utils/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/utils/Image.cpp.i
.PHONY : cpp/utils/Image.cpp.i

cpp/utils/Image.s: cpp/utils/Image.cpp.s
.PHONY : cpp/utils/Image.s

# target to generate assembly for a file
cpp/utils/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/REF.dir/build.make CMakeFiles/REF.dir/cpp/utils/Image.cpp.s
.PHONY : cpp/utils/Image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... REF"
	@echo "... cpp/main.o"
	@echo "... cpp/main.i"
	@echo "... cpp/main.s"
	@echo "... cpp/utils/Image.o"
	@echo "... cpp/utils/Image.i"
	@echo "... cpp/utils/Image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

